version: '3.5'
services:
  nginx: # Load Balancer
    image: nginx:latest
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
   image: postgres
   environment:
    POSTGRES_PASSWORD: "admin"
    POSTGRES_USER: "admin"
   ports:
      - "5435:5432"
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'