version: '3.5'
services:
  nginx: # Load Balancer
    image: nginx:latest
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
   image: postgres
   environment:
    POSTGRES_PASSWORD: "admin"
    POSTGRES_USER: "admin"
   ports:
      - "5435:5432"
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  server:
   image: ubuntu
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  rust_api:
    build:
      context: "../rust"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SES_OWNER: ${SES_OWNER}
      EMAIL_REPORT_FAIL: ${EMAIL_REPORT_FAIL}
      AWS_CURRENT_ACCESS_KEY: ${AWS_CURRENT_ACCESS_KEY}
      AWS_CURRENT_SECRET_ACCESS_KEY: ${AWS_CURRENT_SECRET_ACCESS_KEY}
      AWS_CURRENT_REGION: ${AWS_CURRENT_REGION}
      AWS_CURRENT_ACCOUNT: ${AWS_CURRENT_ACCOUNT}
    